import io
import os
from pathlib import Path

from fastapi import APIRouter, File, HTTPException, UploadFile, status
from fastapi.responses import FileResponse

from app.models.schemas import TrainerRequest, TrainerResponse
from app.services.rag_chain import retrieve_context
from app.services.rag_service import RAGService

router = APIRouter(prefix="/api/v1/trainer", tags=["trainer"])

_DOWNLOADS_DIR = Path("/tmp/trainer_downloads")
_DOWNLOAD_ALLOWED_EXT = {".xlsx"}

TRAINER_SYSTEM_PROMPT = (
    "You are Trainer, focused on employee onboarding and enablement. "
    "Answer strictly from the provided retrieved context. "
    "If evidence is missing in context, say so explicitly and avoid guessing."
)

# ---------------------------------------------------------------------------
# Q&A endpoint
# ---------------------------------------------------------------------------

@router.post("/", response_model=TrainerResponse)
async def trainer_endpoint(request: TrainerRequest):
    question = request.question.strip()
    context = await retrieve_context(question, top_k=6)
    rag = RAGService()
    answer = await rag.generate(
        context=context,
        question=question,
        system_prompt=TRAINER_SYSTEM_PROMPT,
    )
    return TrainerResponse(answer=answer)


# ---------------------------------------------------------------------------
# Document upload -- extract text for session-scoped context injection
# ---------------------------------------------------------------------------

_UPLOAD_ALLOWED_EXT = {".pdf", ".docx", ".txt", ".md", ".csv"}
_MAX_UPLOAD_MB = 20


@router.post("/upload", status_code=status.HTTP_200_OK)
async def trainer_upload(file: UploadFile = File(...)):
    """Extract text from an uploaded document and return it as a string.

    The extracted text is intended for client-side context injection into
    the next Trainer chat message.  It is NOT embedded into ChromaDB.

    Supported formats: PDF, DOCX, TXT, MD, CSV (max 20 MB).
    """
    ext = os.path.splitext(file.filename or "")[-1].lower()
    if ext not in _UPLOAD_ALLOWED_EXT:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail=f"Unsupported file type '{ext}'. Allowed: {', '.join(sorted(_UPLOAD_ALLOWED_EXT))}",
        )

    raw = await file.read()
    if len(raw) > _MAX_UPLOAD_MB * 1024 * 1024:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail=f"File exceeds the {_MAX_UPLOAD_MB} MB limit.",
        )

    try:
        text = _extract_text(ext, raw)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Text extraction failed: {exc}",
        )

    max_chars = 12_000
    truncated = len(text) > max_chars
    if truncated:
        text = text[:max_chars]

    return {
        "filename": file.filename,
        "size_bytes": len(raw),
        "extracted_chars": len(text),
        "truncated": truncated,
        "text": text,
    }


def _extract_text(ext: str, raw: bytes) -> str:
    if ext == ".pdf":
        from pypdf import PdfReader
        reader = PdfReader(io.BytesIO(raw))
        pages = [page.extract_text() or "" for page in reader.pages]
        return "\n".join(pages).strip()

    if ext == ".docx":
        from docx import Document  # python-docx
        doc = Document(io.BytesIO(raw))
        return "\n".join(para.text for para in doc.paragraphs).strip()

    # TXT / MD / CSV
    try:
        return raw.decode("utf-8").strip()
    except UnicodeDecodeError:
        return raw.decode("latin-1", errors="replace").strip()


# ---------------------------------------------------------------------------
# Excel download endpoint (serves files generated by generate_excel tool)
# ---------------------------------------------------------------------------

@router.get("/downloads/{filename}")
async def trainer_download(filename: str):
    """Serve an Excel file previously generated by the Trainer generate_excel tool."""
    if "/" in filename or "\\" in filename or ".." in filename:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid filename.")
    ext = os.path.splitext(filename)[-1].lower()
    if ext not in _DOWNLOAD_ALLOWED_EXT:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Only .xlsx files are served here.")

    filepath = _DOWNLOADS_DIR / filename
    if not filepath.exists():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="File not found or has expired.")

    return FileResponse(
        path=str(filepath),
        filename=filename,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )
